"""
FIX #124: Systematic tag audit — maps all 924 unknown multi_city tags to preference categories.
Run once from travel-planner-backend/ directory.
"""
import ast, re, sys

TAG_ADDITIONS = {
    "attractions_for_kids": [
        "active_family_fun","active_play","africarium","amusement_area",
        "animal_exhibits","animal_specimens","animal_training",
        "arcade_experience","arcade_games","bird_park","bowling",
        "brick_models","butterfly_exhibit_room",
        "candy_workshop","career_simulation","challenge_game",
        "children_animals","children_history",
        "cinema_theme","city_zoo","city_zoo_animals",
        "climbing_challenges","climbing_wall","competitive_fun","console_collection",
        "creative_painting","creative_splatter_art",
        "digital_floor_games","digital_playground",
        "dinosaur_models","dinosaurs","dollhouses",
        "downhill_sledge","downhill_tracks",
        "edutainment","educational_discovery","educational_exhibits",
        "educational_experience","educational_family_attraction",
        "educational_fun","educational_playground","educational_science_displays",
        "electric_gokarts","escape_room","escape_room_game",
        "fairytale_theme","fairytale_trail",
        "family_amusement_area","family_animal_park","family_attraction","family_bike_park",
        "family_boat_trip","family_building_exhibition","family_challenge","family_exhibition",
        "family_experience","family_forest_walk","family_friendly_attraction","family_friendly_route",
        "family_friendly_water","family_fun_center","family_fun_focus","family_learning_center",
        "family_playgrounds","family_relaxation","family_rides",
        "forest_adventure","forest_adventure_park","forest_challenge",
        "fun_activity","fun_experience","fun_labyrinth_challenge","fun_path",
        "games_and_fun","gaming_exhibition",
        "group_activity","group_adventure","group_fun",
        "hands_on_exhibits","hands_on_learning",
        "high_energy_fun","high_stimulation",
        "horse_riding","horse_sleigh_ride",
        "immersive_adventure","immersive_exhibition","immersive_experience","immersive_game",
        "indoor_activity","indoor_aquapark","indoor_aquapark_slides",
        "indoor_attraction","indoor_fun","indoor_inflatable_park","indoor_jump_park","indoor_play_zone",
        "interactive_aircraft_exhibits","interactive_display","interactive_experience",
        "interactive_game_arena","interactive_games","interactive_history","interactive_history_exhibit",
        "interactive_learning","interactive_mind_tricks","interactive_models","interactive_play",
        "interactive_racing","interactive_science","interactive_science_exhibits","interactive_science_garden",
        "interactive_storytelling","interactive_technology_displays","interactive_zones",
        "jumping_zone","kids_entertainment","kids_escape_room","kids_experience","kids_fun","kids_only",
        "laser_arena","laser_tag","laser_tag_arena","learning_through_play",
        "lego_construction_models","lego_exhibition","lego_fan_exhibition","lego_models_collection",
        "live_animals","live_shows","live_tropical_butterflies",
        "logic_puzzles","maze","maze_challenge","mega_theme_park",
        "mini_zoo","miniature_landmarks","miniature_models","minifigure_display","mirror_maze_experience",
        "model_exhibition","model_trains","mystery_adventure","mystery_game",
        "obstacle_courses","optical_illusion_exhibits",
        "outdoor_challenges","outdoor_experience","outdoor_fun",
        "outdoor_physics_experiments","outdoor_puzzle","parrot_house",
        "play_structures","playful_exhibit_rooms","pools_and_slides","puzzle_solving",
        "role_play_city","scenario_game","scenario_games","skill_game",
        "social_activity","soft_play_structures","spider_exhibition","storybook_figures",
        "team_activity","team_battle","team_building","team_challenge","team_game",
        "toy_collection","toy_exhibition","trampoline_arena","tree_climbing",
        "virtual_reality_cinema","vr_zone",
        "visual_illusion_walk","visual_paradox_rooms","visual_tricks",
        "wind_tunnel","zipline_challenges","zipline_routes",
    ],
    "kids_attractions": [
        "active_family_fun","active_play","africarium","amusement_area",
        "animal_exhibits","animal_specimens","animal_training",
        "arcade_experience","arcade_games","bird_park","bowling",
        "brick_models","butterfly_exhibit_room",
        "candy_workshop","career_simulation","challenge_game",
        "children_animals","children_history",
        "cinema_theme","city_zoo","city_zoo_animals",
        "climbing_challenges","climbing_wall","competitive_fun","console_collection",
        "creative_painting","creative_splatter_art",
        "digital_floor_games","digital_playground",
        "dinosaur_models","dinosaurs","dollhouses",
        "downhill_sledge","downhill_tracks",
        "edutainment","educational_discovery","educational_exhibits",
        "educational_experience","educational_family_attraction",
        "educational_fun","educational_playground","educational_science_displays",
        "electric_gokarts","escape_room","escape_room_game",
        "fairytale_theme","fairytale_trail",
        "family_amusement_area","family_animal_park","family_attraction","family_bike_park",
        "family_boat_trip","family_building_exhibition","family_challenge","family_exhibition",
        "family_experience","family_forest_walk","family_friendly_attraction","family_friendly_route",
        "family_friendly_water","family_fun_center","family_fun_focus","family_learning_center",
        "family_playgrounds","family_relaxation","family_rides",
        "forest_adventure","forest_adventure_park","forest_challenge",
        "fun_activity","fun_experience","fun_labyrinth_challenge","fun_path",
        "games_and_fun","gaming_exhibition",
        "group_activity","group_adventure","group_fun",
        "hands_on_exhibits","hands_on_learning",
        "high_energy_fun","high_stimulation",
        "horse_riding","horse_sleigh_ride",
        "immersive_adventure","immersive_exhibition","immersive_experience","immersive_game",
        "indoor_activity","indoor_aquapark","indoor_aquapark_slides",
        "indoor_attraction","indoor_fun","indoor_inflatable_park","indoor_jump_park","indoor_play_zone",
        "interactive_aircraft_exhibits","interactive_display","interactive_experience",
        "interactive_game_arena","interactive_games","interactive_history","interactive_history_exhibit",
        "interactive_learning","interactive_mind_tricks","interactive_models","interactive_play",
        "interactive_racing","interactive_science","interactive_science_exhibits","interactive_science_garden",
        "interactive_storytelling","interactive_technology_displays","interactive_zones",
        "jumping_zone","kids_entertainment","kids_escape_room","kids_experience","kids_fun","kids_only",
        "laser_arena","laser_tag","laser_tag_arena","learning_through_play",
        "lego_construction_models","lego_exhibition","lego_fan_exhibition","lego_models_collection",
        "live_animals","live_shows","live_tropical_butterflies",
        "logic_puzzles","maze","maze_challenge","mega_theme_park",
        "mini_zoo","miniature_landmarks","miniature_models","minifigure_display","mirror_maze_experience",
        "model_exhibition","model_trains","mystery_adventure","mystery_game",
        "obstacle_courses","optical_illusion_exhibits",
        "outdoor_challenges","outdoor_experience","outdoor_fun",
        "outdoor_physics_experiments","outdoor_puzzle","parrot_house",
        "play_structures","playful_exhibit_rooms","pools_and_slides","puzzle_solving",
        "role_play_city","scenario_game","scenario_games","skill_game",
        "social_activity","soft_play_structures","spider_exhibition","storybook_figures",
        "team_activity","team_battle","team_building","team_challenge","team_game",
        "toy_collection","toy_exhibition","trampoline_arena","tree_climbing",
        "virtual_reality_cinema","vr_zone",
        "visual_illusion_walk","visual_paradox_rooms","visual_tricks",
        "wind_tunnel","zipline_challenges","zipline_routes",
    ],
    "theme_parks": [
        "amusement_area","arcade_experience","arcade_games",
        "cinema_theme","competitive_fun","console_collection",
        "creative_painting","creative_splatter_art",
        "digital_floor_games","digital_playground",
        "edutainment","electric_gokarts","escape_room","escape_room_game",
        "extreme_experience","fairytale_theme","fairytale_trail",
        "family_amusement_area","family_fun_center","family_rides",
        "fun_activity","fun_experience","games_and_fun","gaming_exhibition",
        "high_energy_fun","high_stimulation",
        "immersive_adventure","immersive_game",
        "indoor_fun","indoor_inflatable_park","indoor_jump_park","indoor_play_zone",
        "interactive_game_arena","interactive_games","interactive_racing",
        "jumping_zone","laser_arena","laser_tag","laser_tag_arena",
        "lego_construction_models","lego_fan_exhibition",
        "mega_theme_park","mirror_maze_experience",
        "mystery_adventure","mystery_game","night_show",
        "obstacle_courses","optical_illusion_exhibits","outdoor_challenges",
        "paintball_arena","role_play_city",
        "scenario_game","scenario_games","simulator_rides","skill_game",
        "thrill_activity","trampoline_arena","tree_climbing",
        "virtual_reality_cinema","vr_zone",
        "visual_illusion_walk","visual_paradox_rooms","visual_tricks",
        "wild_west_theme","wind_tunnel",
        "zipline_challenges","zipline_routes",
    ],
    "active_sport": [
        "activity_center","adrenaline_experience","adventure_spot","adventure_zone",
        "artificial_wave","beginner_friendly","bowling","bungee_jump","cable_lift",
        "climbing_challenges","climbing_spot","climbing_wall","competitive_fun",
        "dog_sport","downhill_sledge","downhill_tracks","electric_gokarts",
        "extreme_experience","family_bike_park","fitness_path",
        "flight_simulation","forest_adventure","forest_adventure_park","forest_challenge",
        "fun_activity","golf_course","golf_course_resort",
        "group_adventure","group_fun","group_fun_activity",
        "high_energy_fun","high_intensity_activity",
        "horse_riding","horse_sleigh_ride","indoor_track","jumping_zone",
        "laser_arena","laser_tag","laser_tag_arena",
        "mountain_bike","mountain_bike_trails","mountain_chairlift",
        "mountain_fun_ride","mountain_river_rafting",
        "obstacle_courses","offroad_experience",
        "outdoor_challenges","outdoor_experience","outdoor_fun",
        "paintball_arena","physical_activity","pirate_ship_cruise",
        "quad_rides","racing_experience","rock_climbing_spot",
        "rope_obstacles","ropes_course","sea_adventure",
        "ski_resort_slopes","skiing_and_snowboarding",
        "sledging","slides_focus","snow_tubing","solo_friendly_activity",
        "summer_sled_track",
        "team_activity","team_battle","team_challenge","team_game",
        "thrill_activity","trampoline_arena","tree_climbing",
        "wind_tunnel","winter_sports",
        "zipline_challenges","zipline_routes",
    ],
    "museums_heritage": [
        "academic_heritage","action_painting_studio","aircraft_collection",
        "ancient_artifacts_collection","ancient_burial_mound","ancient_legend_site",
        "archaeological_exhibits",
        "architectural_feature","architecture_feature","architecture_icon","architecture_lovers",
        "aristocratic_history","aristocratic_residence",
        "art_center","art_collection","art_exhibition","art_exhibits","art_experience",
        "automotive_history","aviation_history","aviation_history_theme",
        "baroque_basilica","baroque_church_interior",
        "baroque_defensive_system","baroque_fortifications","baroque_hall","baroque_plague_column",
        "car_collection","carriage_collection","cathedral_area",
        "city_history","city_history_exhibits","city_history_walk",
        "city_icon","city_monument","city_symbol",
        "classic_cars","classic_cars_collection","collector_exhibits",
        "communist_history","composer_heritage","concert_hall","concert_venue",
        "contemporary_art","contemporary_art_exhibitions",
        "craft_production","craft_workshop",
        "crystal_displays","crystal_glass",
        "cultural_collection","cultural_district","cultural_events","cultural_heritage_quarter",
        "cultural_history","cultural_institution","cultural_learning",
        "da_vinci_lady_with_ermine","dark_history","distillery_exhibits",
        "early_polish_history","earth_science","earth_science_display","educational_center",
        "engineering_innovations","engineering_landmark",
        "ethnographic_collection","ethnographic_heritage","ethnography",
        "european_masterpieces","evolution_exhibition","flagship_museum",
        "folk_culture_exhibits","folk_culture_experience",
        "galician_jewish_history","gaming_exhibition","gas_production","gemstones_exhibition",
        "glass_factory","glassmaking_tradition","glassmaking_workshop",
        "global_culture_exhibition","gnome_theme",
        "gothic_cathedral","gothic_church_interior","gothic_church_landmark","gothic_defense_architecture",
        "government_building","handcrafted_candy","handcrafted_glass",
        "hands_on_exhibits","hands_on_learning",
        "historic_art_collection","historic_artist_house","historic_bastion","historic_botanical_garden",
        "historic_buildings","historic_cathedral","historic_cellars","historic_cemetery",
        "historic_chopin_manor","historic_church","historic_city_gate","historic_city_park",
        "historic_defense_site","historic_equipment","historic_exhibits",
        "historic_ghetto_site","historic_gold_mining","historic_interiors","historic_island",
        "historic_jewish_district","historic_landmark","historic_market_hall","historic_market_landmark",
        "historic_mining_story","historic_museum","historic_old_town","historic_old_town_square",
        "historic_painting","historic_palace_complex","historic_palace_museum","historic_palace_views",
        "historic_quarry_park","historic_renaissance_palace","historic_ruins",
        "historic_sailing_ship","historic_spa_theatre","historic_square","historic_station",
        "historic_stone_bridge","historic_synagogues","historic_tower","historic_town_hall_tower",
        "historic_town_square","historic_toy_collection","historic_tunnel_route",
        "historic_warship","historic_water_tower",
        "historical_memorial","historical_memory_museum","history_museum","history_site",
        "horse_drawn_vehicles","iconic_altar_artwork","iconic_building","iconic_vessel",
        "immersive_exhibition","immersive_experience","independence_struggle",
        "industrial_architecture","industrial_history","industrial_history_exhibits","industrial_museum",
        "interactive_audio","interactive_history","interactive_history_exhibit","interactive_models",
        "interactive_regional_exhibits","interactive_technology_displays",
        "jan_matejko_heritage","japanese_garden","jewish_culture_exhibits",
        "katyn_massacre","knights_history","krakow_history_exhibits","krakow_legend_site",
        "leaning_tower_landmark","lego_exhibition",
        "literary_exhibition","literary_heritage","literary_house","literary_legend_trail","literary_museum",
        "local_folk_craft","maritime_heritage","maritime_history","matchbox_collection",
        "mechanical_nativity_scene","medieval_castle_ruins",
        "medieval_cellars","medieval_city_gate","medieval_city_landmark","medieval_city_layout",
        "medieval_defensive_tower","medieval_engineering_models","medieval_fortifications",
        "medieval_fortress_ruins","medieval_history","medieval_market_history",
        "medieval_square_landmark","medieval_street_layout","medieval_structure","medieval_tower",
        "memorial_exhibition","memorial_site","migration_history",
        "military_exhibits","military_fort","military_heritage","military_history","military_secret",
        "mineral_and_gemstone_collection","mineral_collection","mineral_collections",
        "missionary_history_exhibits","model_exhibition","model_trains",
        "modern_architecture","modern_art","modern_art_gallery","modern_history","modern_museum",
        "modern_polish_history","money_education",
        "multimedia_exhibits","multimedia_fountain","multimedia_storytelling",
        "music_culture","music_museum",
        "national_art_collection","national_heritage","national_literature","national_memory","national_museum",
        "natural_history_exhibits","naval_history","neon_art",
        "nostalgia_exhibits","nostalgia_lifestyle","nostalgic_family_museum","notable_figures",
        "open_air_ethnographic_museum","open_air_museum","paper_making_history",
        "patriotic_monument","polish_art_history","polish_history","polish_painting","polish_painting_history",
        "polish_resistance_history",
        "prehistoric_archaeology_site","prehistoric_life","prehistoric_models","prehistoric_theme",
        "railway_history","regional_craft","regional_folk_culture","regional_history_exhibits",
        "religious_landmark","religious_museum","remembrance_monument","remembrance_site",
        "renaissance_art_gallery","renaissance_castle_palace","renaissance_castle_residence",
        "retro_gaming","roman_architecture",
        "royal_burials","royal_castle_complex","royal_route","royal_route_landmark","rural_life",
        "schindler_factory","scientific_collection","space_exhibition","specialized_collection",
        "technical_exhibits","time_travel_theme","traditional_christmas_display",
        "traditional_craft","traditional_crafts_display","traditional_crafts_workshops",
        "traditional_culture","traditional_rural_architecture","traditional_world_houses",
        "transport_heritage","transport_history",
        "unique_museum_theme","unique_religious_site","university_complex","vintage_toys_exhibition",
        "vodka_history","vodka_production_history",
        "war_history","war_memory","wartime_artifacts","weapon_collection",
        "writer_house","writer_house_museum","writer_museum","ww2_history","ww2_memorial_square",
    ],
    "museum_heritage": [
        "academic_heritage","action_painting_studio","aircraft_collection",
        "ancient_artifacts_collection","ancient_burial_mound","ancient_legend_site",
        "archaeological_exhibits",
        "architectural_feature","architecture_feature","architecture_icon","architecture_lovers",
        "aristocratic_history","aristocratic_residence",
        "art_center","art_collection","art_exhibition","art_exhibits","art_experience",
        "automotive_history","aviation_history","aviation_history_theme",
        "baroque_basilica","baroque_church_interior",
        "baroque_defensive_system","baroque_fortifications","baroque_hall","baroque_plague_column",
        "car_collection","carriage_collection","cathedral_area",
        "city_history","city_history_exhibits","city_history_walk",
        "city_icon","city_monument","city_symbol",
        "classic_cars","classic_cars_collection","collector_exhibits",
        "communist_history","composer_heritage","concert_hall","concert_venue",
        "contemporary_art","contemporary_art_exhibitions",
        "craft_production","craft_workshop",
        "crystal_displays","crystal_glass",
        "cultural_collection","cultural_district","cultural_events","cultural_heritage_quarter",
        "cultural_history","cultural_institution","cultural_learning",
        "da_vinci_lady_with_ermine","dark_history","distillery_exhibits",
        "early_polish_history","earth_science","earth_science_display","educational_center",
        "engineering_innovations","engineering_landmark",
        "ethnographic_collection","ethnographic_heritage","ethnography",
        "european_masterpieces","evolution_exhibition","flagship_museum",
        "folk_culture_exhibits","folk_culture_experience",
        "galician_jewish_history","gaming_exhibition","gas_production","gemstones_exhibition",
        "glass_factory","glassmaking_tradition","glassmaking_workshop",
        "global_culture_exhibition","gnome_theme",
        "gothic_cathedral","gothic_church_interior","gothic_church_landmark","gothic_defense_architecture",
        "government_building","handcrafted_candy","handcrafted_glass",
        "hands_on_exhibits","hands_on_learning",
        "historic_art_collection","historic_artist_house","historic_bastion","historic_botanical_garden",
        "historic_buildings","historic_cathedral","historic_cellars","historic_cemetery",
        "historic_chopin_manor","historic_church","historic_city_gate","historic_city_park",
        "historic_defense_site","historic_equipment","historic_exhibits",
        "historic_ghetto_site","historic_gold_mining","historic_interiors","historic_island",
        "historic_jewish_district","historic_landmark","historic_market_hall","historic_market_landmark",
        "historic_mining_story","historic_museum","historic_old_town","historic_old_town_square",
        "historic_painting","historic_palace_complex","historic_palace_museum","historic_palace_views",
        "historic_quarry_park","historic_renaissance_palace","historic_ruins",
        "historic_sailing_ship","historic_spa_theatre","historic_square","historic_station",
        "historic_stone_bridge","historic_synagogues","historic_tower","historic_town_hall_tower",
        "historic_town_square","historic_toy_collection","historic_tunnel_route",
        "historic_warship","historic_water_tower",
        "historical_memorial","historical_memory_museum","history_museum","history_site",
        "horse_drawn_vehicles","iconic_altar_artwork","iconic_building","iconic_vessel",
        "immersive_exhibition","immersive_experience","independence_struggle",
        "industrial_architecture","industrial_history","industrial_history_exhibits","industrial_museum",
        "interactive_audio","interactive_history","interactive_history_exhibit","interactive_models",
        "interactive_regional_exhibits","interactive_technology_displays",
        "jan_matejko_heritage","japanese_garden","jewish_culture_exhibits",
        "katyn_massacre","knights_history","krakow_history_exhibits","krakow_legend_site",
        "leaning_tower_landmark","lego_exhibition",
        "literary_exhibition","literary_heritage","literary_house","literary_legend_trail","literary_museum",
        "local_folk_craft","maritime_heritage","maritime_history","matchbox_collection",
        "mechanical_nativity_scene","medieval_castle_ruins",
        "medieval_cellars","medieval_city_gate","medieval_city_landmark","medieval_city_layout",
        "medieval_defensive_tower","medieval_engineering_models","medieval_fortifications",
        "medieval_fortress_ruins","medieval_history","medieval_market_history",
        "medieval_square_landmark","medieval_street_layout","medieval_structure","medieval_tower",
        "memorial_exhibition","memorial_site","migration_history",
        "military_exhibits","military_fort","military_heritage","military_history","military_secret",
        "mineral_and_gemstone_collection","mineral_collection","mineral_collections",
        "missionary_history_exhibits","model_exhibition","model_trains",
        "modern_architecture","modern_art","modern_art_gallery","modern_history","modern_museum",
        "modern_polish_history","money_education",
        "multimedia_exhibits","multimedia_fountain","multimedia_storytelling",
        "music_culture","music_museum",
        "national_art_collection","national_heritage","national_literature","national_memory","national_museum",
        "natural_history_exhibits","naval_history","neon_art",
        "nostalgia_exhibits","nostalgia_lifestyle","nostalgic_family_museum","notable_figures",
        "open_air_ethnographic_museum","open_air_museum","paper_making_history",
        "patriotic_monument","polish_art_history","polish_history","polish_painting","polish_painting_history",
        "polish_resistance_history",
        "prehistoric_archaeology_site","prehistoric_life","prehistoric_models","prehistoric_theme",
        "railway_history","regional_craft","regional_folk_culture","regional_history_exhibits",
        "religious_landmark","religious_museum","remembrance_monument","remembrance_site",
        "renaissance_art_gallery","renaissance_castle_palace","renaissance_castle_residence",
        "retro_gaming","roman_architecture",
        "royal_burials","royal_castle_complex","royal_route","royal_route_landmark","rural_life",
        "schindler_factory","scientific_collection","space_exhibition","specialized_collection",
        "technical_exhibits","time_travel_theme","traditional_christmas_display",
        "traditional_craft","traditional_crafts_display","traditional_crafts_workshops",
        "traditional_culture","traditional_rural_architecture","traditional_world_houses",
        "transport_heritage","transport_history",
        "unique_museum_theme","unique_religious_site","university_complex","vintage_toys_exhibition",
        "vodka_history","vodka_production_history",
        "war_history","war_memory","wartime_artifacts","weapon_collection",
        "writer_house","writer_house_museum","writer_museum","ww2_history","ww2_memorial_square",
    ],
    "nature_landscapes": [
        "balancing_rock","botanical_collection","botanical_tree_collection",
        "city_park","cliff_views","cliffside_views",
        "coastal_landscape","coastal_relaxation","coastal_views","coastal_walks",
        "colorful_lakes","dam_structure",
        "dramatic_cliff_views","dramatic_rock_landscape",
        "eagle_nests_trail","easy_access_nature","environmental_learning","exotic_species",
        "famous_bend","fitness_path",
        "forest_hike","forest_hill_walk","forest_landscape","forest_nature_reserve",
        "forest_park_trails","forest_reserve","forest_setting","forested_hill_walk",
        "granite_cliffs","granite_viewpoint",
        "green_city_walk","green_fields_leisure","green_recreation_area","green_relaxation","greenhouse",
        "harbour_views","health_trail","hikers_rest_point","hiking_paths",
        "hill_viewpoint","hilltop_viewpoint",
        "iconic_hiking_destination","iconic_pier",
        "instagram_photo_spots","japanese_garden",
        "karkonosze_ecosystem","karkonosze_landmark","karkonosze_views",
        "labyrinth_rock_formations","lakeside_relax",
        "landscape_design","landscaped_gardens","landscaped_park_walks","landscaped_walks",
        "large_city_meadow","large_city_park",
        "limestone_cliffs_area","limestone_rock_pillar","memorial_hill",
        "mineral_springs","mountain_cable_car","mountain_chairlift","mountain_experience",
        "mountain_folklore","mountain_hut","mountain_lake_relaxation","mountain_rest_point",
        "mountain_river_rafting","mountain_road_curve","mountain_shelter_stop","mountain_valley",
        "mountain_waterfall",
        "national_park","national_park_attraction","national_park_education_center",
        "natural_curiosity","natural_lake_swimming",
        "nature_education","nature_exhibits","nature_picnic_spot","nature_trail",
        "observation_deck","observation_point",
        "ojcow_national_park_cave","ojcow_national_park_landmark",
        "ojcow_national_park_symbol","ojcow_valley_landmark",
        "open_green_space","open_space","oriental_garden",
        "panoramic_landscape_views","panoramic_old_town_views","panoramic_photo_spot","panoramic_valley_views",
        "park_complex","park_walk","peat_bog_reserve","pedestrian_bridge_sculpture","pergola_structure",
        "plant_exhibits","plants","popular_picnic_spot","protected_landscape",
        "quiet_beach_area","quiet_green_area","quiet_nature_walks",
        "rare_plants_collection","rare_wetland_ecosystem","relax_garden",
        "relaxing_green_space","relaxing_walks","remote_nature",
        "river_access","river_activity","river_views",
        "riverside_island","riverside_landmark","riverside_walk",
        "rock_viewpoint","rooftop_garden","sand_spit_walk",
        "sandstone_corridors","sandstone_rock_formations",
        "scenic_cliffs","scenic_drive","scenic_fortress_views","scenic_hilltop",
        "scenic_mountain_views","scenic_riverside_views","scenic_stop","scenic_stroll",
        "scenic_valley","scenic_valley_landmark","scenic_view_dining","scenic_viewpoints","scenic_views","scenic_walks",
        "sea_panorama","sea_views","small_fishing_pier",
        "stalactite_formations","stone_geological_trail",
        "summer_hotspot","summer_spot",
        "suspension_bridge",
        "table_mountains_landscape","table_mountains_nature","table_mountains_peak","table_mountains_views",
        "turquoise_limestone_lake","unique_colors","unique_landscape","unusual_nature_shapes",
        "urban_hill","urban_lake","urban_lake_beach","urban_square",
        "viewpoint_hill","viewpoint_stop",
        "vistula_photo_spot","vistula_river_walks","vistula_riverside_photo_spot",
        "walking","walking_paths",
        "water_education","water_elements","water_features","water_reservoir","water_viewpoint",
        "waterfront_views",
        "wetlands","wildlife","wildlife_exhibits","wildlife_forest_area","yacht_harbour",
    ],
    "nature_landscape": [
        "balancing_rock","botanical_collection","botanical_tree_collection",
        "city_park","cliff_views","cliffside_views",
        "coastal_landscape","coastal_relaxation","coastal_views","coastal_walks",
        "colorful_lakes","dam_structure",
        "dramatic_cliff_views","dramatic_rock_landscape",
        "eagle_nests_trail","easy_access_nature","environmental_learning","exotic_species",
        "famous_bend","fitness_path",
        "forest_hike","forest_hill_walk","forest_landscape","forest_nature_reserve",
        "forest_park_trails","forest_reserve","forest_setting","forested_hill_walk",
        "granite_cliffs","granite_viewpoint",
        "green_city_walk","green_fields_leisure","green_recreation_area","green_relaxation","greenhouse",
        "harbour_views","health_trail","hikers_rest_point","hiking_paths",
        "hill_viewpoint","hilltop_viewpoint",
        "iconic_hiking_destination","iconic_pier",
        "instagram_photo_spots","japanese_garden",
        "karkonosze_ecosystem","karkonosze_landmark","karkonosze_views",
        "labyrinth_rock_formations","lakeside_relax",
        "landscape_design","landscaped_gardens","landscaped_park_walks","landscaped_walks",
        "large_city_meadow","large_city_park",
        "limestone_cliffs_area","limestone_rock_pillar","memorial_hill",
        "mineral_springs","mountain_cable_car","mountain_chairlift","mountain_experience",
        "mountain_folklore","mountain_hut","mountain_lake_relaxation","mountain_rest_point",
        "mountain_river_rafting","mountain_road_curve","mountain_shelter_stop","mountain_valley",
        "mountain_waterfall",
        "national_park","national_park_attraction","national_park_education_center",
        "natural_curiosity","natural_lake_swimming",
        "nature_education","nature_exhibits","nature_picnic_spot","nature_trail",
        "observation_deck","observation_point",
        "ojcow_national_park_cave","ojcow_national_park_landmark",
        "ojcow_national_park_symbol","ojcow_valley_landmark",
        "open_green_space","open_space","oriental_garden",
        "panoramic_landscape_views","panoramic_old_town_views","panoramic_photo_spot","panoramic_valley_views",
        "park_complex","park_walk","peat_bog_reserve","pedestrian_bridge_sculpture","pergola_structure",
        "plant_exhibits","plants","popular_picnic_spot","protected_landscape",
        "quiet_beach_area","quiet_green_area","quiet_nature_walks",
        "rare_plants_collection","rare_wetland_ecosystem","relax_garden",
        "relaxing_green_space","relaxing_walks","remote_nature",
        "river_access","river_activity","river_views",
        "riverside_island","riverside_landmark","riverside_walk",
        "rock_viewpoint","rooftop_garden","sand_spit_walk",
        "sandstone_corridors","sandstone_rock_formations",
        "scenic_cliffs","scenic_drive","scenic_fortress_views","scenic_hilltop",
        "scenic_mountain_views","scenic_riverside_views","scenic_stop","scenic_stroll",
        "scenic_valley","scenic_valley_landmark","scenic_view_dining","scenic_viewpoints","scenic_views","scenic_walks",
        "sea_panorama","sea_views","small_fishing_pier",
        "stalactite_formations","stone_geological_trail",
        "summer_hotspot","summer_spot",
        "suspension_bridge",
        "table_mountains_landscape","table_mountains_nature","table_mountains_peak","table_mountains_views",
        "turquoise_limestone_lake","unique_colors","unique_landscape","unusual_nature_shapes",
        "urban_hill","urban_lake","urban_lake_beach","urban_square",
        "viewpoint_hill","viewpoint_stop",
        "vistula_photo_spot","vistula_river_walks","vistula_riverside_photo_spot",
        "walking","walking_paths",
        "water_education","water_elements","water_features","water_reservoir","water_viewpoint",
        "waterfront_views",
        "wetlands","wildlife","wildlife_exhibits","wildlife_forest_area","yacht_harbour",
    ],
    "water_attractions": [
        "aqua_park","artificial_wave",
        "coastal_relaxation","dam_structure",
        "family_boat_trip","family_friendly_water",
        "harbour_views","iconic_pier",
        "indoor_aquapark","indoor_aquapark_slides",
        "mountain_river_rafting","natural_lake_swimming","peaceful_seaside","pirate_ship_cruise",
        "pools_and_slides","river_bathing","river_cruise","river_activity",
        "sailing_atmosphere","sea_adventure","seaside_relaxation","slides_focus",
        "summer_swimming_spot","swimming_pool",
        "urban_lake_beach",
        "water_adventure","water_slides","water_zone","waterslides","wave_pool_attraction",
    ],
    "castles_palaces": [
        "aristocratic_residence",
        "baroque_defensive_system","baroque_fortifications",
        "castle_views","city_fortifications","defensive_architecture",
        "dramatic_cliffside_castle","dramatic_cliff_views",
        "eagle_nests_trail","fortress","fortress_complex",
        "gothic_defense_architecture",
        "historic_bastion","historic_defense_site",
        "historic_palace_complex","historic_palace_museum","historic_palace_views",
        "historic_renaissance_palace","historic_ruins",
        "medieval_castle_ruins","medieval_defensive_tower","medieval_fortifications",
        "medieval_fortress_ruins","medieval_structure","medieval_tower",
        "military_fort","mountain_fort_ruins","mountain_fortress_complex",
        "noble_architecture","official_residence",
        "palace_complex","palace_interior",
        "renaissance_castle_palace","renaissance_castle_residence","roman_architecture",
        "royal_burials","royal_castle_complex","royal_route","royal_route_landmark",
        "ruined_castle_tower","ruins_remains","scenic_fortress_views",
    ],
    "caves_mines": [
        "crystal_displays","crystal_glass",
        "earth_science","earth_science_display",
        "geological_phenomenon","geology_exhibition","geology_exhibits","geology_museum_exhibits",
        "gold_mine_tunnels","historic_cellars","historic_gold_mining","historic_mining_story",
        "historic_tunnel_route","human_bone_decorations","interactive_mining_tour",
        "karst_cave_exploration","karst_cave_system",
        "labyrinth_rock_formations","large_karst_cave","limestone_cliffs_area",
        "mine_tour","mineral_and_gemstone_collection","mineral_collection","mineral_collections",
        "mining_tunnels","ossuary_chapel",
        "sandstone_corridors","sandstone_rock_formations","stalactite_formations",
        "stone_geological_trail",
        "underground_archaeology","underground_corridors","underground_exploration",
        "underground_nature","underground_project","underground_tunnels","underground_waterfall",
        "uranium_mine_tunnels","uranium_mining",
    ],
    "relax_wellness": [
        "coastal_relaxation","family_relaxation","green_relaxation",
        "health","health_resort_experience","health_resort_tradition","health_trail",
        "lakeside_relax","leisure","leisure_activity","leisure_space",
        "mineral_springs","mineral_water_tasting",
        "mountain_lake_relaxation","nature_picnic_spot","open_green_space","peaceful_seaside",
        "relax_experience","relax_garden","relax_zone","relaxation_area",
        "relaxing_green_space","relaxing_sport","relaxing_walks",
        "salt_room","sauna_zone","seaside_relaxation","short_relax_session",
        "spa_attraction","spa_experience","spa_park_gardens","spa_promenade",
        "spa_sauna_complex","spa_town_viewpoint","spa_tradition","spa_water_tasting","spa_zone",
        "summer_relax","thermal_relax_focus","thermal_relaxation","urban_relax",
        "water_adventure","waterfront_leisure","waterside_relaxation",
        "wellness_experience","wellness_zone",
    ],
    "relaxation": [
        "coastal_relaxation","family_relaxation","green_relaxation",
        "health","health_resort_experience","health_resort_tradition","health_trail",
        "lakeside_relax","leisure","leisure_activity","leisure_space",
        "mineral_springs","mineral_water_tasting",
        "mountain_lake_relaxation","nature_picnic_spot","open_green_space","peaceful_seaside",
        "relax_experience","relax_garden","relax_zone","relaxation_area",
        "relaxing_green_space","relaxing_sport","relaxing_walks",
        "salt_room","sauna_zone","seaside_relaxation","short_relax_session",
        "spa_attraction","spa_experience","spa_park_gardens","spa_promenade",
        "spa_sauna_complex","spa_town_viewpoint","spa_tradition","spa_water_tasting","spa_zone",
        "summer_relax","thermal_relax_focus","thermal_relaxation","urban_relax",
        "water_adventure","waterfront_leisure","waterside_relaxation",
        "wellness_experience","wellness_zone",
    ],
    "local_food_experience": [
        "cafes_and_restaurants","candy_workshop","culinary_workshop",
        "dessert_spot","distillery_exhibits","english_pub","food_hall",
        "handcrafted_candy","local_market_life","mineral_water_tasting",
        "polish_spirits_tasting","restaurants_and_cafes","restaurants_shops",
        "sports_bar","sweets_experience","traditional_craft",
        "vodka_history","vodka_production_history",
    ],
    "history_mystery": [
        "ancient_burial_mound","ancient_legend_site","battle_scene",
        "communist_history","dark_history","early_polish_history",
        "escape_room","escape_room_game","frankenstein_story_route",
        "galician_jewish_history","hidden_clues",
        "historic_ghetto_site","historic_jewish_district","historic_ruins",
        "historical_memorial","historical_memory_museum","history_museum","history_site",
        "immersive_game","independence_struggle",
        "jan_matejko_heritage","jewish_culture_exhibits",
        "katyn_massacre","kids_escape_room","knights_history",
        "krakow_history_exhibits","krakow_legend_site",
        "labyrinth_rock_formations","legend_place","legend_story","literary_legend_trail",
        "logic_puzzles","maze","maze_challenge",
        "medieval_history","medieval_market_history",
        "memorial_exhibition","memorial_hill","memorial_place","memorial_site",
        "migration_history","military_history","military_secret","mine_tour",
        "modern_polish_history","mystery_adventure","mystery_game",
        "national_literature","national_memory","ossuary_chapel",
        "patriotic_monument","polish_resistance_history","political_prison",
        "prehistoric_archaeology_site","prison_history","puzzle_solving",
        "religious_landmark","remembrance_monument","remembrance_site",
        "royal_burials","scenario_game","scenario_games","schindler_factory",
        "socialist_realism_architecture","time_travel_theme","underground_archaeology",
        "war_history","war_memory","wartime_artifacts","weapon_collection",
        "writer_house","writer_house_museum","writer_museum",
        "ww2_history","ww2_memorial_square",
    ],
    "mountain_trails": [
        "cable_lift","coastal_walks","eagle_nests_trail",
        "fitness_path","forest_hike","forest_hill_walk",
        "forest_nature_reserve","forest_park_trails","forested_hill_walk",
        "granite_viewpoint","health_trail",
        "hikers_rest_point","hiking_paths","hill_viewpoint","hilltop_viewpoint",
        "iconic_hiking_destination",
        "karkonosze_landmark","karkonosze_views","labyrinth_rock_formations",
        "mountain_bike","mountain_bike_trails","mountain_cable_car","mountain_chairlift",
        "mountain_experience","mountain_hut","mountain_rest_point",
        "mountain_road_curve","mountain_shelter_stop","mountain_valley","mountain_waterfall",
        "national_park_attraction","nature_trail",
        "ojcow_national_park_landmark","ojcow_valley_landmark",
        "quiet_nature_walks","rock_climbing_spot",
        "scenic_cliffs","scenic_drive","scenic_hilltop","scenic_mountain_views",
        "scenic_valley","scenic_valley_landmark",
        "stone_geological_trail","summer_sled_track","suspension_bridge",
        "table_mountains_landscape","table_mountains_nature","table_mountains_peak","table_mountains_views",
        "trailhead_parking","unique_landscape",
        "viewpoint_hill","viewpoint_stop","walking","walking_paths",
    ],
}

def patch():
    filepath = "app/domain/scoring/tag_preferences.py"
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Parse the file to find USER_PREFERENCES_TO_TAGS
    # We'll do it by string manipulation — find each preference key's tags list
    # and append new tags that aren't already present

    total_added = 0
    skipped_already_present = 0

    for pref_key, new_tags in TAG_ADDITIONS.items():
        # Find the section for this preference key
        # Pattern: "pref_key": { ... "tags": [ ... ], "tag_bonus": N }
        # We need to find the closing ] of the tags list for this preference

        # Find the preference key occurrence
        key_pattern = f'"{pref_key}"'
        key_idx = content.find(key_pattern)
        if key_idx == -1:
            print(f"WARNING: preference key '{pref_key}' not found in file!")
            continue

        # Find "tags": [ after the key
        tags_section_start = content.find('"tags": [', key_idx)
        if tags_section_start == -1:
            print(f"WARNING: 'tags' list not found for '{pref_key}'!")
            continue

        # Find the closing bracket of the tags list
        # We need to find the ] that closes this list
        # Count brackets from the [ onwards
        bracket_start = content.find('[', tags_section_start)
        depth = 0
        bracket_end = bracket_start
        for i in range(bracket_start, len(content)):
            if content[i] == '[':
                depth += 1
            elif content[i] == ']':
                depth -= 1
                if depth == 0:
                    bracket_end = i
                    break

        # Get the existing tags list content
        existing_list_str = content[bracket_start:bracket_end+1]

        # Find which new tags are already present
        tags_to_add = []
        for tag in new_tags:
            if f'"{tag}"' in existing_list_str:
                skipped_already_present += 1
            else:
                tags_to_add.append(tag)

        if not tags_to_add:
            print(f"  [{pref_key}]: all {len(new_tags)} tags already present")
            continue

        # Build insertion string
        fix_comment = f"\n            # FIX #124: Systematic tag audit\n"
        tag_lines = "".join(f'            "{t}",\n' for t in tags_to_add)
        insertion = fix_comment + tag_lines

        # Insert before the closing bracket
        # Find the position just before the closing ]
        # The closing ] is at bracket_end
        insert_pos = bracket_end

        content = content[:insert_pos] + insertion + "        " + content[insert_pos:]
        total_added += len(tags_to_add)
        print(f"  [{pref_key}]: added {len(tags_to_add)} tags")

    print(f"\nTotal added: {total_added} tag entries")
    print(f"Already present (skipped): {skipped_already_present}")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"File updated: {filepath}")

if __name__ == "__main__":
    patch()
