"""FIX145 add tags column to restaurants

Revision ID: 244f1ce34ad9
Revises: 9d2c36bb967a
Create Date: 2026-06-01 17:56:15.540934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244f1ce34ad9'
down_revision: Union[str, None] = '9d2c36bb967a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'tags')
    # ### end Alembic commands ###
