"""ETAP 3: Add restaurants and trails tables

Revision ID: 9d2c36bb967a
Revises: 1574e2d13f08
Create Date: 2026-04-26 09:28:42.748808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2c36bb967a'
down_revision: Union[str, None] = '1574e2d13f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('meal_type', sa.String(length=10), nullable=False),
    sa.Column('cuisine_type', sa.String(length=100), nullable=True),
    sa.Column('place_type', sa.String(length=100), nullable=True),
    sa.Column('visit_duration_min', sa.Integer(), server_default='60', nullable=False),
    sa.Column('visit_duration_max', sa.Integer(), server_default='90', nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('opening_hours_seasonal', sa.JSON(), nullable=True),
    sa.Column('price_level', sa.Integer(), server_default='2', nullable=False),
    sa.Column('avg_meal_cost', sa.Integer(), server_default='50', nullable=False),
    sa.Column('atmosphere', sa.String(length=100), nullable=True),
    sa.Column('space', sa.String(length=50), nullable=True),
    sa.Column('reservations_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('target_group', sa.JSON(), nullable=True),
    sa.Column('children_friendly', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('popularity_score', sa.Numeric(precision=4, scale=2), server_default='0.0', nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('must_try', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parking_name', sa.String(length=255), nullable=True),
    sa.Column('parking_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('parking_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('parking_walk_time_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pro_tip', sa.Text(), nullable=True),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('link_website', sa.Text(), nullable=True),
    sa.Column('link_menu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_restaurants_city_meal_type', 'restaurants', ['city', 'meal_type'], unique=False)
    op.create_index('idx_restaurants_location', 'restaurants', ['lat', 'lng'], unique=False)
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index(op.f('ix_restaurants_meal_type'), 'restaurants', ['meal_type'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_table('trails',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('trail_name', sa.String(length=255), nullable=False),
    sa.Column('peak_name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('trail_color', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('length_km', sa.Numeric(precision=6, scale=2), server_default='0.0', nullable=False),
    sa.Column('elevation_gain_m', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_min', sa.Integer(), server_default='120', nullable=False),
    sa.Column('time_max', sa.Integer(), server_default='180', nullable=False),
    sa.Column('best_season', sa.String(length=100), nullable=True),
    sa.Column('family_friendly', sa.Boolean(), nullable=False),
    sa.Column('exposure_level', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('weather_dependency', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('technical_difficulty', sa.String(length=50), nullable=True),
    sa.Column('start_point_name', sa.String(length=255), nullable=True),
    sa.Column('start_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('start_lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('start_elevation_m', sa.Integer(), server_default='0', nullable=False),
    sa.Column('end_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('target_group', sa.JSON(), nullable=True),
    sa.Column('children_min_age', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parking_name', sa.String(length=255), nullable=True),
    sa.Column('parking_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('parking_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('parking_walk_time_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parking_type', sa.String(length=50), nullable=True),
    sa.Column('parking_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('pro_tip', sa.Text(), nullable=True),
    sa.Column('popularity_score', sa.Numeric(precision=4, scale=2), server_default='0.0', nullable=False),
    sa.Column('scenic_score', sa.Numeric(precision=4, scale=2), server_default='0.0', nullable=False),
    sa.Column('must_do', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('link_map', sa.Text(), nullable=True),
    sa.Column('link_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trails_family_friendly', 'trails', ['family_friendly'], unique=False)
    op.create_index('idx_trails_location', 'trails', ['start_lat', 'start_lng'], unique=False)
    op.create_index('idx_trails_region_difficulty', 'trails', ['region', 'difficulty_level'], unique=False)
    op.create_index(op.f('ix_trails_difficulty_level'), 'trails', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_trails_family_friendly'), 'trails', ['family_friendly'], unique=False)
    op.create_index(op.f('ix_trails_region'), 'trails', ['region'], unique=False)
    op.create_index(op.f('ix_trails_trail_name'), 'trails', ['trail_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trails_trail_name'), table_name='trails')
    op.drop_index(op.f('ix_trails_region'), table_name='trails')
    op.drop_index(op.f('ix_trails_family_friendly'), table_name='trails')
    op.drop_index(op.f('ix_trails_difficulty_level'), table_name='trails')
    op.drop_index('idx_trails_region_difficulty', table_name='trails')
    op.drop_index('idx_trails_location', table_name='trails')
    op.drop_index('idx_trails_family_friendly', table_name='trails')
    op.drop_table('trails')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_meal_type'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_index('idx_restaurants_location', table_name='restaurants')
    op.drop_index('idx_restaurants_city_meal_type', table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
