"""add auth and payment tables

Revision ID: d86ff6a86132
Revises: 360e3cae0377
Create Date: 2026-02-23 23:49:32.472077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd86ff6a86132'
down_revision: Union[str, None] = '360e3cae0377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('supabase_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('payment_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PLN', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_sessions_plan_id'), 'payment_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payment_sessions_status'), 'payment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_sessions_stripe_session_id'), 'payment_sessions', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_payment_sessions_user_id'), 'payment_sessions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('payment_session_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PLN', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_session_id'], ['payment_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_plan_id'), 'transactions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_transactions_stripe_payment_intent'), 'transactions', ['stripe_payment_intent'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_index('ix_plan_versions_version_number', table_name='plan_versions')
    op.add_column('plans', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('plans', 'group_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plans', 'budget_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'trip_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_plans_location'), 'plans', ['location'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_foreign_key(None, 'plans', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_location'), table_name='plans')
    op.alter_column('plans', 'trip_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'budget_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'group_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('plans', 'user_id')
    op.create_index('ix_plan_versions_version_number', 'plan_versions', ['version_number'], unique=False)
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_stripe_payment_intent'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_plan_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_sessions_user_id'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_stripe_session_id'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_status'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_plan_id'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
